api/urls.py
from django.conf.urls import url
from .views import PostListView, PostDetailView

urlpatterns = [
    url(r'^posts/$', PostListView.as_view(), name='post_list'),
    url(r'^posts/(?P<pk>\d+)/$', PostDetailView.as_view(), name='post_detail')
]

blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^search/$', views.post_search, name='post_search'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/', include('api.urls', namespace='api')),
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80, verbose_name='名字')
    email = models.EmailField(verbose_name='邮箱')
    body = models.TextField(verbose_name='评论内容')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created', )
    def __str__(self):
        return '{}提交的关于{}的评论'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='名字')
    email = forms.EmailField(label='邮箱')
    to = forms.EmailField(label='发送到')
    comments = forms.CharField(required=False, widget=forms.Textarea, label='评论')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

api/views.py
from django.shortcuts import render
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from api.serializers import PostSerializer
from blog.models import Post

# Create your views here.
class PostListView(ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticatedOrReadOnly,)

class PostDetailView(RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    authentication_classes = (BasicAuthentication,)
    permission_classes = (IsAuthenticatedOrReadOnly,)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet
from django.views.generic import ListView, DetailView
# Create your views here.

def post_list(request, tag_slug=None):
    form = SearchForm
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(1)
    context = {'page':page, 'posts':posts, 'tag':tag, 'form':form}
    return render(request, 'blog/post/list.html', context)

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {'post':post, 'comments':comments, 'new_comment':new_comment, 'comment_form':comment_form,
               'similar_posts':similar_posts}
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # Read "get_absolute_url()" at http://127.0.0.1:8000/blog/2018/07/07/get_absolute_url/    可点击
            #post_url = post.get_absolute_url()   #Read "get_absolute_url()" at /blog/2018/07/07/get_absolute_url/ 无法点击
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'shepherd-xing@outlook.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
        cd = None
    return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent, 'cd':cd})

def post_search(request):
    form = SearchForm()
    cd = None
    results = None
    total_results = None
    if request.GET.get('query'):
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            total_results = results.count()
    context = {'form':form, 'cd':cd, 'results':results, 'total_results':total_results}

    return render(request, 'blog/post/search.html', context)

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script>
        $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
            })
    </script>
</head>
<body>
    <div id="content">
        <h1><a href="{% url 'blog:post_list' %}">月明星稀的博客</a></h1>
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>月明星稀的博客</h2>
        <p>月明星稀，乌鹊南飞。<br>绕树三匝，何枝可依？</p>
        <h3>搜索文章</h3>
        <form action="{% url 'blog:post_search' %}" method="get">
            <input type="text" name="query" style="background:white">
            <input type="submit" value="搜索">
        </form>
        <div style="clear:both"></div>
        <p>共有{% total_posts %}篇文章。</p>
        <p><a href="{% url 'blog:post_feed' %}">订阅到我的RSS feed</a></p>
        <h3>最新的文章</h3>
        {% show_latest_posts 3 %}
        <h3>评论最多的文章</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
             第{{ page.number }}页 / 共{{ page.paginator.num_pages }}页
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    <p class="tags">标签：
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},
            {% endif %}
        {% endfor %}
    </p>

    {{ post.body|linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
        分享这篇文章
        </a>
    </p>
    <h2>相似的文章</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        没有相似的文章。
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }}条评论
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                第{{ forloop.counter }}条评论，{{ comment.name }}在{{ comment.created }}提交
            </p>
            <p id="comment-content">{{ comment.body|markdown }}</p>
        </div>
    {% empty %}
        <p>还没有任何评论。</p>
    {% endfor %}
    {% if new_comment %}
        <h2>您的评论已经提交。</h2>
    {% else %}
        <h2>添加一条新评论</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input id="btn" type="submit" value="评论"></p>
        </form>
    {% endif %}

<script>
    $(document).ready(function(){
        $("#btn1").click(function(){
            var name=$("#id_name").val();
            var email=$("#id_email").val();
            var body=$("#id_body").val();
            $.post('.', {'name':name, 'email':email, 'body':body}, function(data){
                console.log('ok');
        })
    })
</script>
{% endblock %}

templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}首页{% endblock %}

{% block content %}
    {% if tag %}
        <h2>标签为{{ tag.name }}的文章</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            {{ forloop.counter }}:
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            <p class="tags">标签：
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                    {% if not forloop.last %} ,
                    {% endif %}
                {% endfor %}
                </p>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatechars_html:130 }}
    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}
{% endblock %}

templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}搜索{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <h1>包含{{ cd.query }}的文章</h1>
        <h3>找到{{ total_results }}项结果</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|slice:'100' }}
            {% endwith %}
            {% empty %}
                <p>什么也没找到！</p>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}分享帖子{% endblock %}

{% block content %}
    {% if sent %}
        <h1>邮件成功发送</h1>
        <p>
            "{{ post.title }}"成功发送到{{ cd.to }}。
        </p>
    {% else %}
        <h1>通过邮件分享"{{ post.title }}"</h1>
        <form action="." method="post">
           {# {{ form.as_p }} #}
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="发送邮件">
        </form>
    {% endif %}
{% endblock %}